# Generated by Django 4.2.2 on 2023-06-16 21:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('on_call', '0001_initial'),
        ('meta_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=50, verbose_name='模板名称')),
                ('template_content', models.JSONField(default=dict, verbose_name='模板内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('alert_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_template', to='meta_info.alertmode', verbose_name='告警方式')),
            ],
            options={
                'verbose_name': '告警模板',
                'verbose_name_plural': '告警模板',
            },
        ),
        migrations.CreateModel(
            name='AlertTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=50, verbose_name='对象名称')),
                ('target_content', models.CharField(max_length=200, verbose_name='对象地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('alert_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_target', to='meta_info.alertmode', verbose_name='告警方式')),
            ],
            options={
                'verbose_name': '告警对象',
                'verbose_name_plural': '告警对象',
            },
        ),
        migrations.CreateModel(
            name='AlertSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('source_id', models.CharField(max_length=50, unique=True, verbose_name='源ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('monitoring_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_source', to='meta_info.monitoringsystem', verbose_name='监控系统')),
            ],
            options={
                'verbose_name': '告警源',
                'verbose_name_plural': '告警源',
            },
        ),
        migrations.CreateModel(
            name='AlertRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=50, verbose_name='规则名称')),
                ('week_day', multiselectfield.db.fields.MultiSelectField(choices=[(0, '周一'), (1, '周二'), (2, '周三'), (3, '周四'), (4, '周五'), (5, '周六'), (6, '周日')], default=[0, 1, 2, 3, 4, 5, 6], max_length=30, verbose_name='周')),
                ('start_time', models.TimeField(default=datetime.time(0, 0), verbose_name='开始时间')),
                ('end_time', models.TimeField(default=datetime.time(23, 59, 59), verbose_name='终止时间')),
                ('alert_object', models.CharField(blank=True, max_length=200, verbose_name='告警对象')),
                ('alert_object_operator', models.SmallIntegerField(choices=[(0, '不包含'), (1, '包含')], default=0, verbose_name='操作符')),
                ('alert_object_ip', models.CharField(default='0.0.0.0', max_length=200, verbose_name='告警对象IP')),
                ('alert_object_ip_operator', models.SmallIntegerField(choices=[(0, '不匹配'), (1, '匹配')], default=0, verbose_name='操作符')),
                ('alert_object_groups', models.CharField(blank=True, max_length=200, verbose_name='告警对象属组')),
                ('alert_object_groups_operator', models.SmallIntegerField(choices=[(0, '不包含'), (1, '包含')], default=0, verbose_name='操作符')),
                ('alert_content', models.CharField(blank=True, max_length=200, verbose_name='告警内容')),
                ('alert_content_operator', models.SmallIntegerField(choices=[(0, '不包含'), (1, '包含')], default=0, verbose_name='操作符')),
                ('alert_object_label', models.JSONField(default=dict, verbose_name='告警对象标签')),
                ('alert_object_label_operator', models.SmallIntegerField(choices=[(0, '不包含'), (1, '包含')], default=0, verbose_name='操作符')),
                ('alert_level', models.SmallIntegerField(choices=[(0, '未分类'), (1, '信息'), (2, '警告'), (3, '一般严重'), (4, '严重'), (5, '灾难')], verbose_name='告警级别')),
                ('monitor_template', models.CharField(blank=True, max_length=200, verbose_name='监控模板')),
                ('monitor_template_operator', models.SmallIntegerField(choices=[(0, '不包含'), (1, '包含')], default=0, verbose_name='操作符')),
                ('additional_args', models.JSONField(default=dict, verbose_name='告警方式附属参数')),
                ('is_on_call', models.BooleanField(default=False, verbose_name='是否同步值班信息')),
                ('is_working', models.BooleanField(default=True, verbose_name='是否开启')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('alert_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='meta_info.alertmode', verbose_name='告警方式')),
                ('alert_source', models.ManyToManyField(related_name='alert_rules', to='alerting.alertsource', verbose_name='告警源')),
                ('alert_target', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='alert_mode', chained_model_field='alert_mode', on_delete=django.db.models.deletion.CASCADE, to='alerting.alerttarget', verbose_name='告警对象')),
                ('alert_template', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='alert_mode', chained_model_field='alert_mode', on_delete=django.db.models.deletion.CASCADE, to='alerting.alerttemplate', verbose_name='告警模板')),
                ('assigned_roles', models.ManyToManyField(related_name='alert_rules', to='on_call.oncallrole', verbose_name='分配角色')),
            ],
            options={
                'verbose_name': '告警规则',
                'verbose_name_plural': '告警规则',
            },
        ),
        migrations.CreateModel(
            name='AlertContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=50, verbose_name='告警ID')),
                ('alert_object', models.CharField(max_length=200, verbose_name='告警对象')),
                ('alert_object_ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='告警对象IP')),
                ('alert_object_groups', models.JSONField(default=list, verbose_name='告警对象属组')),
                ('alert_object_label', models.JSONField(default=dict, verbose_name='告警对象标签')),
                ('alert_content', models.CharField(max_length=200, verbose_name='告警内容')),
                ('alert_level', models.SmallIntegerField(choices=[(0, '未分类'), (1, '信息'), (2, '警告'), (3, '一般严重'), (4, '严重'), (5, '灾难')], verbose_name='告警级别')),
                ('monitor_template', models.CharField(blank=True, max_length=200, verbose_name='监控模板')),
                ('alert_status', models.CharField(choices=[('firing', '警报'), ('ok', '正常'), ('unknown', '未知')], max_length=20, verbose_name='告警状态')),
                ('latest_value', models.CharField(max_length=200, verbose_name='最新值')),
                ('trigger_time', models.DateTimeField(blank=True, null=True, verbose_name='告警触发时间')),
                ('recovery_time', models.DateTimeField(blank=True, null=True, verbose_name='告警恢复时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('alert_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_content', to='alerting.alertsource', verbose_name='告警源')),
                ('assigned_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_content', to='on_call.oncallrole', verbose_name='分配角色')),
                ('assigned_stuff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_content', to='on_call.oncallstuff', verbose_name='分配人员')),
            ],
            options={
                'verbose_name': '告警内容',
                'verbose_name_plural': '告警内容',
                'unique_together': {('alert_source', 'alert_id')},
            },
        ),
    ]
