# Generated by Django 4.2.2 on 2023-06-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrules',
            name='alert_content_operator',
            field=models.SmallIntegerField(choices=[(0, '不包含'), (1, '包含')], default=1, verbose_name='操作符'),
        ),
        migrations.AlterField(
            model_name='alertrules',
            name='alert_object_groups_operator',
            field=models.SmallIntegerField(choices=[(0, '不包含'), (1, '包含')], default=1, verbose_name='操作符'),
        ),
        migrations.AlterField(
            model_name='alertrules',
            name='alert_object_ip_operator',
            field=models.SmallIntegerField(choices=[(0, '不匹配'), (1, '匹配')], default=1, verbose_name='操作符'),
        ),
        migrations.AlterField(
            model_name='alertrules',
            name='alert_object_label_operator',
            field=models.SmallIntegerField(choices=[(0, '不包含'), (1, '包含')], default=1, verbose_name='操作符'),
        ),
        migrations.AlterField(
            model_name='alertrules',
            name='alert_object_operator',
            field=models.SmallIntegerField(choices=[(0, '不包含'), (1, '包含')], default=1, verbose_name='操作符'),
        ),
        migrations.AlterField(
            model_name='alertrules',
            name='monitor_template_operator',
            field=models.SmallIntegerField(choices=[(0, '不包含'), (1, '包含')], default=1, verbose_name='操作符'),
        ),
    ]
