# Generated by Django 4.2.2 on 2023-06-17 07:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alerting', '0002_alter_alertrules_alert_content_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrules',
            name='alert_level',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, '周一'), (1, '周二'), (2, '周三'), (3, '周四'), (4, '周五'), (5, '周六'), (6, '周日')], default=[3, 4, 5], max_length=50, verbose_name='告警级别'),
        ),
    ]
