# Generated by Django 4.2.2 on 2023-06-17 07:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alerting', '0003_alter_alertrules_alert_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrules',
            name='alert_level',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, '未分类'), (1, '信息'), (2, '警告'), (3, '一般严重'), (4, '严重'), (5, '灾难')], default=[3, 4, 5], max_length=50, verbose_name='告警级别'),
        ),
    ]
