# Generated by Django 4.2.2 on 2023-06-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerting', '0004_alter_alertrules_alert_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrules',
            name='additional_args',
            field=models.JSONField(blank=True, default=dict, verbose_name='告警方式附属参数'),
        ),
        migrations.AlterField(
            model_name='alertrules',
            name='alert_object_label',
            field=models.JSONField(blank=True, default=dict, verbose_name='告警对象标签'),
        ),
    ]
