# Generated by Django 4.2.2 on 2023-06-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerting', '0005_alter_alertrules_additional_args_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrules',
            name='alert_content',
            field=models.CharField(blank=True, max_length=200, verbose_name='告警内容(关键字)'),
        ),
        migrations.AlterField(
            model_name='alertrules',
            name='alert_content_operator',
            field=models.SmallIntegerField(choices=[(1, '不包含'), (0, '包含')], default=1, verbose_name='操作符'),
        ),
        migrations.AlterField(
            model_name='alertrules',
            name='alert_object_groups_operator',
            field=models.SmallIntegerField(choices=[(1, '不包含'), (0, '包含')], default=1, verbose_name='操作符'),
        ),
        migrations.AlterField(
            model_name='alertrules',
            name='alert_object_ip_operator',
            field=models.SmallIntegerField(choices=[(1, '不匹配'), (0, '匹配')], default=1, verbose_name='操作符'),
        ),
        migrations.AlterField(
            model_name='alertrules',
            name='alert_object_label_operator',
            field=models.SmallIntegerField(choices=[(1, '不包含'), (0, '包含')], default=1, verbose_name='操作符'),
        ),
        migrations.AlterField(
            model_name='alertrules',
            name='alert_object_operator',
            field=models.SmallIntegerField(choices=[(1, '不包含'), (0, '包含')], default=1, verbose_name='操作符'),
        ),
        migrations.AlterField(
            model_name='alertrules',
            name='monitor_template_operator',
            field=models.SmallIntegerField(choices=[(1, '不包含'), (0, '包含')], default=1, verbose_name='操作符'),
        ),
    ]
