# Generated by Django 4.2.2 on 2023-06-20 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerting', '0008_alertinhibition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertcontent',
            name='alert_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_content', to='alerting.alertsource', verbose_name='告警源'),
        ),
    ]
