# Generated by Django 4.2.2 on 2023-06-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerting', '0009_alter_alertcontent_alert_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertcontent',
            name='acknowledge_info',
            field=models.TextField(blank=True, max_length=200, verbose_name='确认信息'),
        ),
        migrations.AddField(
            model_name='alertcontent',
            name='manually_close',
            field=models.BooleanField(default=False, verbose_name='手动关闭'),
        ),
    ]
