version: '3'

services:
  alerts_center_mysql:
    image: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    expose:
      - "3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=p?juqS0Q.3#e
      - MYSQL_DATABASE=alerts
      - MYSQL_USER=alerts
      - MYSQL_PASSWORD=p?juqS0Q.3#e

  alerts_center_redis:
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./data/redis/redis.conf:/etc/redis.conf
      - ./data/redis/data/:/data
    expose:
      - "6379"
    restart: always

  alerts_center_django:
    build: .
    links:
      - alerts_center_mysql:alerts_center_mysql
      - alerts_center_redis:alerts_center_redis
    environment:
      - SERVICE_HOST=127.0.0.1
      - SECRET_KEY=django-insecure-61bfvkzts-cj%qj9p5tt*b(5kp9ca2quvv&i)gm-1=oonbabj6
      - DJANGO_PROFILE=production
      - DB_HOST=alerts_center_mysql
      - DB_NAME=alerts
      - DB_USER=alerts
      - DB_PASSWORD=p?juqS0Q.3#e
      - CELERY_BROKER_DB_HOST=alerts_center_redis
      - CELERY_BROKER_DB_PORT=6379
      - CELERY_BROKER_DB_PASSWORD=DcispVlX&g
    ports:
      - "9988:9009"
    depends_on:
      - alerts_center_mysql
      - alerts_center_redis

  alerts_center_celery:
    build: .
    links:
      - alerts_center_mysql:alerts_center_mysql
      - alerts_center_redis:alerts_center_redis
      - alerts_center_django:alerts_center_django
    environment:
      - DJANGO_PROFILE=production
      - DB_HOST=alerts_center_mysql
      - DB_NAME=alerts
      - DB_USER=alerts
      - DB_PASSWORD=p?juqS0Q.3#e
      - CELERY_BROKER_DB_HOST=alerts_center_redis
      - CELERY_BROKER_DB_PORT=6379
      - CELERY_BROKER_DB_PASSWORD=DcispVlX&g
    command: run_celery
    depends_on:
      - alerts_center_mysql
      - alerts_center_redis
      - alerts_center_django
