version: '3'

services:
  alerts_center_mysql:
    image: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  alerts_center_redis:
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./data/redis/redis.conf:/etc/redis.conf
      - ./data/redis/data/:/data
    expose:
      - "6379"

  alerts_center_django:
    build: .
    links:
      - alerts_center_mysql:alerts_center_mysql
      - alerts_center_redis:alerts_center_redis
    environment:
      - SERVICE_HOST
      - SECRET_KEY
      - DJANGO_PROFILE
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - CELERY_BROKER_DB_HOST
      - CELERY_BROKER_DB_PORT
      - CELERY_BROKER_DB_PASSWORD
    ports:
      - "9988:9009"
    depends_on:
      - alerts_center_mysql
      - alerts_center_redis

  alerts_center_celery:
    build: .
    links:
      - alerts_center_mysql:alerts_center_mysql
      - alerts_center_redis:alerts_center_redis
      - alerts_center_django:alerts_center_django
    environment:
      - DJANGO_PROFILE
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - CELERY_BROKER_DB_HOST
      - CELERY_BROKER_DB_PORT
      - CELERY_BROKER_DB_PASSWORD
    command: run_celery
    depends_on:
      - alerts_center_mysql
      - alerts_center_redis
      - alerts_center_django
