# Generated by Django 4.2.2 on 2023-06-16 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnCallRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
                ('role_desc', models.CharField(blank=True, max_length=50, verbose_name='角色描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '值班角色',
                'verbose_name_plural': '值班角色',
            },
        ),
        migrations.CreateModel(
            name='OnCallStuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('stuff_phone_number', models.CharField(max_length=11, unique=True, verbose_name='手机号码')),
                ('stuff_email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('on_call_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_call_stuff', to='on_call.oncallrole', verbose_name='值班角色')),
            ],
            options={
                'verbose_name': '值班人员',
                'verbose_name_plural': '值班人员',
            },
        ),
    ]
