# Generated by Django 4.2.2 on 2023-06-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_call', '0003_oncalltable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncalltable',
            name='sequence',
            field=models.JSONField(default=dict, verbose_name='序列'),
        ),
    ]
