# Generated by Django 4.2.2 on 2023-06-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_name', models.CharField(max_length=20, unique=True, verbose_name='名称')),
                ('module_path', models.CharField(max_length=100, verbose_name='类路径')),
                ('module_name', models.CharField(max_length=100, verbose_name='类名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '告警方式',
                'verbose_name_plural': '告警方式',
            },
        ),
        migrations.CreateModel(
            name='MonitoringSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '监控系统',
                'verbose_name_plural': '监控系统',
            },
        ),
    ]
