# Generated by Django 4.2.2 on 2023-06-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_info', '0002_alertmode_additional_attrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsystem',
            name='key',
            field=models.CharField(blank=True, max_length=50, verbose_name='Key'),
        ),
    ]
