# Generated by Django 4.2.2 on 2023-06-20 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerting', '0008_alertinhibition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configure_name', models.CharField(default='默认配置', max_length=40, verbose_name='配置名称')),
                ('update_on_call_switch', models.BooleanField(default=False, verbose_name='更新值班表')),
                ('update_on_call_time', models.TimeField(default=datetime.time(17, 0), verbose_name='更新时间')),
                ('clean_alert_inhibition_expired_switch', models.BooleanField(default=True, verbose_name='清理过期的告警抑制规则')),
                ('clean_alert_inhibition_expired_period', models.SmallIntegerField(default=5, verbose_name='更新周期')),
                ('clean_alert_inhibition_expired_unit', models.CharField(choices=[('minutes', '分钟'), ('hours', '小时')], default='minutes', max_length=20, verbose_name='单位')),
                ('unresolved_alerts_reminder_switch', models.BooleanField(default=False, verbose_name='未恢复告警提醒')),
                ('unresolved_alerts_reminder_period', models.SmallIntegerField(default=1, verbose_name='提醒周期')),
                ('unresolved_alerts_reminder_unit', models.CharField(choices=[('minutes', '分钟'), ('hours', '小时')], default='hours', max_length=20, verbose_name='单位')),
                ('unresolved_alerts_reminder_type', models.CharField(choices=[('dingding', '钉钉'), ('feishu', '飞书')], default='dingding', max_length=20, verbose_name='通知方式')),
                ('unresolved_alerts_reminder_webhook', models.CharField(default='请设置', max_length=200, verbose_name='通知Webhook')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('alert_source', models.ManyToManyField(blank=True, to='alerting.alertsource', verbose_name='需要提醒的告警源')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
    ]
