# Generated by Django 4.2.2 on 2023-06-21 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0004_alter_systemconfigure_alert_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfigure',
            name='send_on_call_info_reminder_type',
            field=models.CharField(choices=[('dingding', '钉钉'), ('feishu', '飞书')], default='dingding', max_length=20, verbose_name='通知方式'),
        ),
        migrations.AddField(
            model_name='systemconfigure',
            name='send_on_call_info_reminder_webhook',
            field=models.CharField(default='请设置', max_length=200, verbose_name='通知Webhook'),
        ),
        migrations.AddField(
            model_name='systemconfigure',
            name='send_on_call_info_switch',
            field=models.BooleanField(default=False, verbose_name='推送值班信息'),
        ),
        migrations.AddField(
            model_name='systemconfigure',
            name='send_on_call_info_time',
            field=models.TimeField(default=datetime.time(8, 40), verbose_name='推送时间'),
        ),
    ]
